set(root "${CMAKE_CURRENT_LIST_DIR}/..")
set(board "${root}/boards/stm32f469i_disco")
foreach(name display_touch msp_uart_f469)
  if(NOT EXISTS "${board}/ports/${name}.c")
    message(FATAL_ERROR "Missing F469 port ${name}")
  endif()
endforeach()
file(READ "${board}/ports/display_touch.c" display)
foreach(required BSP_LCD_Init BSP_TS_Init LCD_FB_START_ADDRESS lv_display_set_flush_cb)
  if(NOT display MATCHES "${required}")
    message(FATAL_ERROR "Display/touch port missing ${required}")
  endif()
endforeach()
file(READ "${board}/ports/msp_uart_f469.c" uart)
foreach(required USART6 GPIOC GPIO_PIN_6 GPIO_PIN_7 UART_OVERSAMPLING_16)
  if(NOT uart MATCHES "${required}")
    message(FATAL_ERROR "MSP port missing ${required}")
  endif()
endforeach()
file(READ "${board}/ports/ws2812_f469.c" leds)
foreach(required GPIOB GPIO_PIN_4 GPIO_PIN_5 GPIO_AF2_TIM3)
  if(NOT leds MATCHES "${required}")
    message(FATAL_ERROR "WS2812 port missing ${required}")
  endif()
endforeach()
if(uart MATCHES "GPIOG" OR leds MATCHES "GPIOC")
  message(FATAL_ERROR "CN12 UART/WS2812 pin ownership is stale")
endif()
if(display MATCHES "stm32h7|wio_lite" OR uart MATCHES "stm32h7|wio_lite")
  message(FATAL_ERROR "F469 port imports H7/Wio headers")
endif()
