set(root "${CMAKE_CURRENT_LIST_DIR}/..")
set(ui "${root}/App/Src/ui/f469_ui.c")
set(face "${root}/App/Src/ui/f469_face.c")
set(info "${root}/App/Src/ui/f469_info.c")
foreach(file "${ui}" "${face}" "${info}")
  if(NOT EXISTS "${file}")
    message(FATAL_ERROR "F469 UI source missing: ${file}")
  endif()
endforeach()
file(READ "${ui}" ui_text)
foreach(required f469_face_create f469_info_create two_screen_swipe two_screen_select_main "DEMO")
  if(NOT ui_text MATCHES "${required}")
    message(FATAL_ERROR "F469 UI missing ${required}")
  endif()
endforeach()
if(ui_text MATCHES "screen_showcase_create")
  message(FATAL_ERROR "F469 UI still creates old showcase page")
endif()
