set(root "${CMAKE_CURRENT_LIST_DIR}/..")
set(board "${root}/boards/stm32f469i_disco")
foreach(required README.md pin-map.md CMakeLists.txt STM32F469NIHX_FLASH.ld)
  if(NOT EXISTS "${board}/${required}")
    message(FATAL_ERROR "F469 board target missing ${required}")
  endif()
endforeach()
file(READ "${board}/pin-map.md" pins)
foreach(signal MSP_TX MSP_RX WS_CHAIN_A WS_CHAIN_B LAMP_FRONT LAMP_ROOF)
  if(NOT pins MATCHES "${signal}")
    message(FATAL_ERROR "F469 pin map missing ${signal}")
  endif()
endforeach()
file(READ "${board}/CMakeLists.txt" target)
if(target MATCHES "stm32h7xx|boot_stub|wio_lite_ai")
  message(FATAL_ERROR "F469 target depends on H7/Wio sources")
endif()
