get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(TARGET_FILES
    "${PROJECT_ROOT}/App/Src/platform/ws2812_port.c"
    "${PROJECT_ROOT}/Core/Src/tim.c"
    "${PROJECT_ROOT}/Core/Src/spi.c"
    "${PROJECT_ROOT}/Core/Src/stm32h7xx_it.c"
    "${PROJECT_ROOT}/Core/Src/stm32h7xx_hal_msp.c")

set(TARGET_TEXT "")
foreach(target_file IN LISTS TARGET_FILES)
    file(READ "${target_file}" file_text)
    string(APPEND TARGET_TEXT "\n${file_text}")
endforeach()
file(READ "${PROJECT_ROOT}/Core/Src/tim.c" TIM_TEXT)
file(READ "${PROJECT_ROOT}/App/Src/platform/ws2812_port.c" PORT_TEXT)
file(READ "${PROJECT_ROOT}/Core/Src/stm32h7xx_it.c" IRQ_TEXT)
file(READ "${PROJECT_ROOT}/Core/Inc/stm32h7xx_it.h" IRQ_HEADER_TEXT)
file(READ "${PROJECT_ROOT}/Core/Src/stm32h7xx_hal_msp.c" MSP_TEXT)
file(READ "${PROJECT_ROOT}/Core/Src/spi.c" SPI_TEXT)
file(READ "${PROJECT_ROOT}/Core/Inc/spi.h" SPI_HEADER_TEXT)
file(READ "${PROJECT_ROOT}/Core/Src/main.c" MAIN_TEXT)
file(READ "${PROJECT_ROOT}/Makefile" MAKE_TEXT)
file(READ "${PROJECT_ROOT}/cmake/st-project.cmake" CMAKE_TEXT)
file(READ "${PROJECT_ROOT}/wio_ai.ioc" IOC_TEXT)
string(REPLACE "\\" "/" CMAKE_TEXT "${CMAKE_TEXT}")
string(REPLACE "//" "/" CMAKE_TEXT "${CMAKE_TEXT}")

function(require_text literal)
    string(FIND "${TARGET_TEXT}" "${literal}" found_at)
    if(found_at EQUAL -1)
        message(FATAL_ERROR "Required WS2812 timer wiring is missing: ${literal}")
    endif()
endfunction()

function(reject_text literal)
    string(FIND "${TARGET_TEXT}" "${literal}" found_at)
    if(NOT found_at EQUAL -1)
        message(FATAL_ERROR "Rejected legacy WS2812 wiring is present: ${literal}")
    endif()
endfunction()

function(require_in source_text literal owner)
    string(FIND "${source_text}" "${literal}" found_at)
    if(found_at EQUAL -1)
        message(FATAL_ERROR "${owner} is missing required WS2812 ownership: ${literal}")
    endif()
endfunction()

function(reject_in source_text literal owner)
    string(FIND "${source_text}" "${literal}" found_at)
    if(NOT found_at EQUAL -1)
        message(FATAL_ERROR "${owner} retains rejected WS2812 ownership: ${literal}")
    endif()
endfunction()

function(require_safe_low_before_init port pins)
    set(write_call "HAL_GPIO_WritePin(${port}, ${pins}, GPIO_PIN_RESET)")
    string(FIND "${TIM_TEXT}" "${write_call}" write_at)
    if(write_at EQUAL -1)
        message(FATAL_ERROR "Missing safe-low write: ${write_call}")
    endif()

    string(SUBSTRING "${TIM_TEXT}" ${write_at} -1 after_write)
    string(FIND "${after_write}" "GPIO_InitStruct.Pin = ${pins}" pin_at)
    string(FIND "${after_write}" "HAL_GPIO_Init(${port}, &GPIO_InitStruct)" init_at)
    if(pin_at EQUAL -1 OR init_at EQUAL -1 OR pin_at GREATER init_at)
        message(FATAL_ERROR
            "Safe-low write is not before the corresponding ${port} ${pins} init")
    endif()
endfunction()

require_text("GPIO_AF1_TIM2")
require_text("GPIO_AF14_TIM24")
require_text("DMA_REQUEST_TIM2_UP")
require_text("DMA_REQUEST_TIM24_UP")
require_text("TIM_DMABASE_CCR1")
require_text("TIM_DMABURSTLENGTH_2TRANSFERS")
require_text("ws2812_timer_clock_hz()")
require_text("ws2812_compare_ticks(")
require_text("GPIO_PIN_0")
require_text("GPIO_PIN_3")
require_text("GPIO_PIN_11 | GPIO_PIN_12")
require_text("ws2812_timer_fail_safe")
require_text("ws2812_dma_fail_safe")
require_text("TIM_DMABURSTLENGTH_2TRANSFERS,\n            (uint32_t)(slots * 2u)) != HAL_OK) {\n        ws2812_pair_stop(pair, NULL)")
reject_text("HAL_SPI_Transmit_DMA")
reject_text("period_ticks / 3u")
reject_text("(period_ticks * 2u) / 3u")

foreach(stale_spi3 IN ITEMS
        "SPI3" "hspi3" "hdma_spi3_tx" "DMA_REQUEST_SPI3_TX"
        "GPIO_AF6_SPI3")
    reject_in("${MSP_TEXT}" "${stale_spi3}" "stm32h7xx_hal_msp.c")
    reject_in("${IRQ_TEXT}" "${stale_spi3}" "stm32h7xx_it.c")
    reject_in("${IRQ_HEADER_TEXT}" "${stale_spi3}" "stm32h7xx_it.h")
    reject_in("${IOC_TEXT}" "${stale_spi3}" "wio_ai.ioc")
endforeach()
reject_in("${IRQ_TEXT}" "DMA1_Stream1_IRQHandler" "stm32h7xx_it.c")
reject_in("${IRQ_HEADER_TEXT}" "DMA1_Stream1_IRQHandler" "stm32h7xx_it.h")
reject_in("${IOC_TEXT}" "NVIC.DMA1_Stream1_IRQn" "wio_ai.ioc")

require_in("${MSP_TEXT}" "hdma->Instance = DMA1_Stream2;" "TIM2 DMA MSP")
require_in("${MSP_TEXT}" "hdma->Init.Request = DMA_REQUEST_TIM2_UP;" "TIM2 DMA MSP")
require_in("${MSP_TEXT}" "HAL_NVIC_SetPriority(DMA1_Stream2_IRQn, 5, 0);" "TIM2 DMA MSP")
require_in("${MSP_TEXT}" "hdma->Instance = DMA1_Stream3;" "TIM24 DMA MSP")
require_in("${MSP_TEXT}" "hdma->Init.Request = DMA_REQUEST_TIM24_UP;" "TIM24 DMA MSP")
require_in("${MSP_TEXT}" "HAL_NVIC_SetPriority(DMA1_Stream3_IRQn, 5, 0);" "TIM24 DMA MSP")
require_in("${IRQ_TEXT}" "HAL_DMA_IRQHandler(&hdma_tim2_up);" "TIM2 DMA IRQ")
require_in("${IRQ_TEXT}" "HAL_DMA_IRQHandler(&hdma_tim24_up);" "TIM24 DMA IRQ")
require_in("${PORT_TEXT}" "void HAL_TIM_PeriodElapsedCallback" "WS2812 completion callback")
require_in("${PORT_TEXT}" "void HAL_TIM_ErrorCallback" "WS2812 error callback")

require_in("${IOC_TEXT}" "Instance=DMA1_Stream2" "wio_ai.ioc TIM2 stream")
require_in("${IOC_TEXT}" "Instance=DMA1_Stream3" "wio_ai.ioc TIM24 stream")
require_in("${IOC_TEXT}" "NVIC.DMA1_Stream2_IRQn=true\\:5\\:0" "wio_ai.ioc TIM2 priority")
require_in("${IOC_TEXT}" "NVIC.DMA1_Stream3_IRQn=true\\:5\\:0" "wio_ai.ioc TIM3 priority")
require_in("${IOC_TEXT}" "PF11.Signal=S_TIM24_CH1" "wio_ai.ioc PF11 ownership")
require_in("${IOC_TEXT}" "PF12.Signal=S_TIM24_CH2" "wio_ai.ioc PF12 ownership")
require_in("${IOC_TEXT}" "PG13.Signal=SPI6_SCK" "wio_ai.ioc SPI6 SCK ownership")
require_in("${IOC_TEXT}" "PB4.Signal=SPI6_MISO" "wio_ai.ioc SPI6 MISO ownership")
require_in("${IOC_TEXT}" "PB5.Signal=SPI6_MOSI" "wio_ai.ioc SPI6 MOSI ownership")
require_in("${SPI_TEXT}" "hspi6.Instance = SPI6;" "SPI6 initialization")
require_in("${SPI_TEXT}" "SPI_POLARITY_HIGH" "SPI6 IMU mode 3")
require_in("${SPI_TEXT}" "SPI_PHASE_2EDGE" "SPI6 IMU mode 3")
require_in("${SPI_HEADER_TEXT}" "IMU_CS_Pin" "IMU chip select API")
require_in("${MAIN_TEXT}" "MX_SPI6_Init();" "main startup")
require_in("${MAKE_TEXT}" "Core/Src/spi.c" "Makefile")
require_in("${CMAKE_TEXT}" "Core/Src/spi.c" "cmake/st-project.cmake")
reject_in("${IOC_TEXT}" "PB4.Signal=S_TIM3_CH1" "wio_ai.ioc released PB4")
reject_in("${IOC_TEXT}" "PB5.Signal=S_TIM3_CH2" "wio_ai.ioc released PB5")
reject_in("${TIM_TEXT}" "GPIO_PIN_2" "tim.c PA2 exclusion")
reject_in("${PORT_TEXT}" "GPIO_PIN_2" "ws2812_port.c PA2 exclusion")
reject_in("${IOC_TEXT}" "PA2.Signal=S_TIM2" "wio_ai.ioc PA2 exclusion")

function(require_exactly_once source_text literal manifest_name)
    string(REGEX MATCHALL "${literal}" matches "${source_text}")
    list(LENGTH matches match_count)
    if(NOT match_count EQUAL 1)
        message(FATAL_ERROR
            "${manifest_name} must list App/Src/platform/ws2812_port.c exactly once; found ${match_count}")
    endif()
endfunction()

require_exactly_once("${MAKE_TEXT}"
    "App/Src/platform/ws2812_port\\.c" "Makefile")
require_exactly_once("${CMAKE_TEXT}"
    "App/Src/platform/ws2812_port\\.c" "cmake/st-project.cmake")

require_safe_low_before_init("GPIOA" "GPIO_PIN_0")
require_safe_low_before_init("GPIOB" "GPIO_PIN_3")
require_safe_low_before_init("GPIOF" "GPIO_PIN_11 | GPIO_PIN_12")
