param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$root = Join-Path $repo 'Middlewares\Third_Party\lvgl\src'
$sources = Get-ChildItem -LiteralPath $root -Recurse -File -Filter *.c |
    ForEach-Object { $_.FullName.Substring($repo.Length + 1).Replace('\', '/') } |
    Sort-Object

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Generated by scripts/lvgl_sources.ps1; do not edit.')
$lines.Add('LVGL_SOURCES := \')
for ($i = 0; $i -lt $sources.Count; ++$i) {
    $suffix = if ($i -lt ($sources.Count - 1)) { ' \' } else { '' }
    $lines.Add("$($sources[$i])$suffix")
}
$lines.Add('LVGL_OBJECTS := \')
for ($i = 0; $i -lt $sources.Count; ++$i) {
    $relative = $sources[$i].Substring('Middlewares/Third_Party/lvgl/src/'.Length)
    $object = '$(BUILD_DIR)/lvgl/' + $relative.Substring(0, $relative.Length - 2) + '.o'
    $suffix = if ($i -lt ($sources.Count - 1)) { ' \' } else { '' }
    $lines.Add("$object$suffix")
}
$lines.Add('-include $(LVGL_OBJECTS:.o=.d)')

$directory = Split-Path -Parent $OutputPath
if ($directory -and !(Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
}
$utf8NoBom = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($OutputPath, (($lines -join "`n") + "`n"), $utf8NoBom)
